"""Add sentiment column

Revision ID: 164f6a7c0848
Revises: 
Create Date: 2025-01-31 23:48:40.901236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164f6a7c0848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('topics', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_column('topics')
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
